config/routes.rb
Craigslist::Application.routes.draw do

  match "/" => 'categories#index'
  match '/register' => 'users#new'
  match "/sign_in" => 'sessions#new'
  match "/sign_out" => 'sessions#destroy'

  resources :posts, :categories, :users
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :posts
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :content, :category_id
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  has_many :posts

    include BCrypt

    def password
      @password ||= Password.new(password_hash)
    end

    def password=(new_password)
      @password = Password.create(new_password)
      self.password_hash = @password
    end

    def authenticate(password)
      return self if self.password == password
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    User.find_by_id(session[:user_id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create(params[:category])
    redirect_to category_path(@category)
  end

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category])
    redirect_to category_path(@category)
  end

  def destroy
    Category.destroy(params[:id])
    redirect_to categories_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    if current_user
      @post = current_user.posts.create(params[:post])
      redirect_to post_path(@post)
    else
      redirect_to new_session_path
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update_attributes(params[:post])
    redirect_to post_path(@post)
  end

  def destroy
    Post.destroy(params[:id])
    redirect_to posts_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    #render form
  end

  def create
    session[:user_id] = User.find_by_email(params[:user][:email]).authenticate(params[:user][:password])
    redirect_to categories_path
  end

  def destroy
    session.clear
    redirect_to categories_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(params[:user])
    redirect_to categories_path
  end

  def edit
    @user = User.find(params[:id])
  end 

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    redirect_to users_path
  end

  def destroy
    User.destroy(params[:id])
    redirect_to users_path
  end

  def show
    @user = User.find(params[:id])
    @logged_in = (@user == current_user)
    @posts = @user.posts
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/views/categories/_form.html.erb
<%= form_for @category do |f|%>
  <%= label_tag :name %>
  <%= f.text_field :name %><br>
  <%= f.submit %>
<% end %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<%= link_to "New Category", new_category_path %>
<hr>

<% @categories.each do |category| %>
  <div>
    <%= link_to category.name, category_path(category) %>
    <%= link_to "Edit", edit_category_path(category) %> <%= link_to "Delete", category_path(category), method: :delete %></div>

<% end %>

app/views/categories/show.html.erb
<div><%= @category.name %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_list_posts.html.erb
<%= link_to "New Post", new_post_path %>

<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post_path(post) %>
      <% if @logged_in %>
        <%= link_to "Edit", edit_post_path(post) %>
        <%= link_to "Delete", post_path(post), method: :delete %></li>
      <% end %>
  <% end %>
</ul>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :content %>
  <%= f.text_area(:content, size: "50x6") %><br>
  <%= f.label :category_id %>
  <%= collection_select :post, :category_id, Category.all, :id, :name %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render "form" %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<%= render :partial => "partials/list_posts" %>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<div><%= @post.content %></div>

app/views/users/_form.erb
<%= form_for @user do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= label_tag "user[password]", "Password"  %>
<%= text_field_tag "user[password]"%>
<%= f.submit %>
<% end %>

app/views/users/_form_edit.erb
<%= form_for @user do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= label_tag "user[password]", "Password"  %>
<%= text_field_tag "user[password]"%>
<%= f.submit %>
<% end %>

app/views/users/_form_new.erb
<%= form_tag("/users/create", method: "post") do %>
<%= label_tag "user[email]", "Email" %>
<%= text_field_tag "user[email]" %>
<%= label_tag "user[password]", "Password"  %>
<%= text_field_tag "user[password]"%>
<%= submit_tag %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit a user!</h1>


<%= render "form" %>

app/views/users/index.html.erb
<h1>Users</h1> <%= link_to "New User", new_user_path %>
<ul>
  <% @users.each do |user| %>
  <li><%= user.email %> <%= link_to "Edit", edit_user_path(user) %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Create a new user!</h1>


<%= render "form" %>

app/views/users/show.html.erb
<h3><%= @user.email %></h3>
<%= render :partial => "partials/list_posts" %>